<a href="https://colab.research.google.com/github/anaberereta-hue/Trabajos-Colab/blob/main/taller_datos_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [350]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [351]:
df=pd.read_csv('/content/dirty_cafe_sales.csv')

In [352]:
df

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [353]:
df.duplicated()
df.duplicated().sum()

np.int64(0)

¿Cuáles son las columnas presentes en el dataset?

In [354]:
df.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

¿Cuáles son los tipos de datos presentes en el data set?

In [355]:
df.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

¿Cuántos datos nulos existen por cada categoría?

In [356]:
df.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

¿Qué indica la columna Transaction ID? ¿Las cantidades son únicas?

In [357]:
#La columna Transaction ID indica el número de identificacion de cada transacción hecha.
df['Transaction ID'].unique()

array(['TXN_1961373', 'TXN_4977031', 'TXN_4271903', ..., 'TXN_5255387',
       'TXN_7695629', 'TXN_6170729'], dtype=object)

Analiza la columna Item cuantos valores únicos tiene?

In [358]:
df['Item'].unique()

array(['Coffee', 'Cake', 'Cookie', 'Salad', 'Smoothie', 'UNKNOWN',
       'Sandwich', nan, 'ERROR', 'Juice', 'Tea'], dtype=object)

In [359]:
len(df['Item'].unique())

11

In [360]:
#define un arreglo que contiene los valores únicos de la columna 'Item'
columns=df['Item'].unique()

In [361]:
#Para cada item imprime los valores únicos
for item in columns:
    prices = df[df['Item'] == item]['Price Per Unit'].unique()
    print(item, prices)

Coffee ['2.0' nan 'ERROR' 'UNKNOWN']
Cake ['3.0' nan 'UNKNOWN' 'ERROR']
Cookie ['1.0' 'UNKNOWN' nan 'ERROR']
Salad ['5.0' 'ERROR' 'UNKNOWN' nan]
Smoothie ['4.0' nan 'UNKNOWN' 'ERROR']
UNKNOWN ['3.0' '1.0' '5.0' '4.0' '1.5' '2.0' nan 'UNKNOWN' 'ERROR']
Sandwich ['4.0' nan 'ERROR' 'UNKNOWN']
nan []
ERROR ['1.5' '3.0' '5.0' nan '4.0' '2.0' '1.0' 'UNKNOWN' 'ERROR']
Juice ['3.0' nan 'UNKNOWN' 'ERROR']
Tea ['1.5' nan 'ERROR' 'UNKNOWN']

Para cada uno de los items coloca el precio correcto

In [362]:
df['Price Per Unit'].unique()

array(['2.0', '3.0', '1.0', '5.0', '4.0', '1.5', nan, 'ERROR', 'UNKNOWN'],
      dtype=object)

In [363]:
#Se uso la IA para para que corrigiera el codigo que se coloco para que pudiera funcionar, y coloco &, este código se puede reutilizar
#para eliminar en items, y precios por unidad
df.loc[(df['Item'] == 'Coffee') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 2.0
df.loc[(df['Item'] == 'Coffee') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 2.0

In [364]:
df.loc[(df['Item'] == 'Cake') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 3.0
df.loc[(df['Item'] == 'Cake') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 3.0

In [365]:
df.loc[(df['Item'] == 'Cookie') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 1.0
df.loc[(df['Item'] == 'Cookie') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 1.0

In [366]:
df.loc[(df['Item'] == 'Salad') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 5.0
df.loc[(df['Item'] == 'Salad') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 5.0

In [367]:
df.loc[(df['Item'] == 'Smoothie') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 4.0
df.loc[(df['Item'] == 'Smoothie') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 4.0

In [368]:
df.loc[(df['Item'] == 'Sandwich') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 4.0
df.loc[(df['Item'] == 'Sandwich') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 4.0

In [369]:
df.loc[(df['Item'] == 'Juice') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 3.0
df.loc[(df['Item'] == 'Juice') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 3.0

In [370]:
df.loc[(df['Item'] == 'Tea') & (df['Price Per Unit'] == 'ERROR'), 'Price Per Unit'] = 1.5
df.loc[(df['Item'] == 'Tea') & (df['Price Per Unit'] == 'UNKNOWN'), 'Price Per Unit'] = 1.5

In [371]:
for item in columns:
    prices = df[df['Item'] == item]['Price Per Unit'].unique()
    print(item, prices)

Coffee ['2.0' nan 2.0]
Cake ['3.0' nan 3.0]
Cookie ['1.0' 1.0 nan]
Salad ['5.0' 5.0 nan]
Smoothie ['4.0' nan 4.0]
UNKNOWN ['3.0' '1.0' '5.0' '4.0' '1.5' '2.0' nan 'UNKNOWN' 'ERROR']
Sandwich ['4.0' nan 4.0]
nan []
ERROR ['1.5' '3.0' '5.0' nan '4.0' '2.0' '1.0' 'UNKNOWN' 'ERROR']
Juice ['3.0' nan 3.0]
Tea ['1.5' nan 1.5]

En este caso UNKNOWN ['3.0' '1.0' '5.0' '4.0' '1.5' '2.0' nan 'UNKNOWN' 'ERROR'] en base al precio coloca en el item UNKNOWKN el item correspondiente

In [372]:
df.loc[(df['Item'] == 'UNKNOWN') & (df['Price Per Unit'] == '1.0'), 'Item'] = 'Cookie'
df.loc[(df['Item'] == 'UNKNOWN') & (df['Price Per Unit'] == '5.0'), 'Item'] = 'Salad'
df.loc[(df['Item'] == 'UNKNOWN') & (df['Price Per Unit'] == '1.5'), 'Item'] = 'Tea'
df.loc[(df['Item'] == 'UNKNOWN') & (df['Price Per Unit'] == '2.0'), 'Item'] = 'Coffee'

In [373]:
#Saber cuantos datos esta identificacod como UNKNOWN en Item
len(df[df['Item'] == 'UNKNOWN'])

165

In [374]:
#Eliminamos 165 datos debido a que se desconce la diferencia de UNKNOWN con dos precios diferentes, para evitar el sesgo de error
df = df[df['Item'] != 'UNKNOWN']

In [375]:
#Confirmar que ya no haya datos con UNKNOWN
len(df[df['Item'] == 'UNKNOWN'])

0

In [376]:
for item in columns:
    prices = df[df['Item'] == item]['Price Per Unit'].unique()
    print(item, prices)

Coffee ['2.0' nan 2.0]
Cake ['3.0' nan 3.0]
Cookie ['1.0' 1.0 nan]
Salad ['5.0' 5.0 nan]
Smoothie ['4.0' nan 4.0]
UNKNOWN []
Sandwich ['4.0' nan 4.0]
nan []
ERROR ['1.5' '3.0' '5.0' nan '4.0' '2.0' '1.0' 'UNKNOWN' 'ERROR']
Juice ['3.0' nan 3.0]
Tea ['1.5' nan 1.5]

En el caso ERROR ['1.5' '3.0' '5.0' nan '4.0' '2.0' '1.0' 'UNKNOWN' 'ERROR'] en base al precio coloca el item correspondiente en lugar de error

In [377]:
df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '1.5'), 'Item'] = 'Tea'
df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '5.0'), 'Item'] = 'Salad'
df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '2.0'), 'Item'] = 'Coffee'
df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '1.0'), 'Item'] = 'Cookie'

/tmp/ipykernel_2244/1409745170.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '1.5'), 'Item'] = 'Tea'
/tmp/ipykernel_2244/1409745170.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '5.0'), 'Item'] = 'Salad'
/tmp/ipykernel_2244/1409745170.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '2.0'), 'Item'] = 'Coffee'
/tmp/ipykernel_2244/1409745170.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['Item'] == 'ERROR') & (df['Price Per Unit'] == '1.0'), 'Item'] = 'Cookie'

In [378]:
for item in columns:
    prices = df[df['Item'] == item]['Price Per Unit'].unique()
    print(item, prices)

Coffee ['2.0' nan 2.0]
Cake ['3.0' nan 3.0]
Cookie ['1.0' 1.0 nan]
Salad ['5.0' 5.0 nan]
Smoothie ['4.0' nan 4.0]
UNKNOWN []
Sandwich ['4.0' nan 4.0]
nan []
ERROR ['3.0' nan '4.0' 'UNKNOWN' 'ERROR']
Juice ['3.0' nan 3.0]
Tea ['1.5' nan 1.5]

In [379]:
len(df[df['Item'] == 'ERROR'])

151

In [380]:
df = df[df['Item'] != 'ERROR']
len(df[df['Item'] == 'ERROR'])

0

In [381]:
df['Price Per Unit'] = df['Price Per Unit'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Price Per Unit']=df['Price Per Unit'].astype(float)

In [382]:
for item in columns:
    prices = df[df['Item'] == item]['Price Per Unit'].unique()
    print(item, prices)

Coffee [ 2. nan]
Cake [ 3. nan]
Cookie [ 1. nan]
Salad [ 5. nan]
Smoothie [ 4. nan]
UNKNOWN []
Sandwich [ 4. nan]
nan []
ERROR []
Juice [ 3. nan]
Tea [1.5 nan]

In [383]:
#Se uso IA para poder cambiar NaN a sus precios correspondientes segun su item
df.loc[(df['Item'] == 'Cookie') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 1.0
df.loc[(df['Item'] == 'Salad') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 5.0
df.loc[(df['Item'] == 'Tea') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 1.5
df.loc[(df['Item'] == 'Coffee') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 2.0
df.loc[(df['Item'] == 'Cake') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 3.0
df.loc[(df['Item'] == 'Smoothie') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 4.0
df.loc[(df['Item'] == 'Sandwich') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 4.0
df.loc[(df['Item'] == 'Juice') & (df['Price Per Unit'].isna()), 'Price Per Unit'] = 3.0

In [384]:
for item in columns:
    prices = df[df['Item'] == item]['Price Per Unit'].unique()
    print(item, prices)

Coffee [2.]
Cake [3.]
Cookie [1.]
Salad [5.]
Smoothie [4.]
UNKNOWN []
Sandwich [4.]
nan []
ERROR []
Juice [3.]
Tea [1.5]

En las columnas 'total spent y quantity reemplaza los valores desconocidos por np.nan y convierte en tipo float esa columna, realiza lo mismo con la columna quantity

In [385]:
df['Total Spent'] = df['Total Spent'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Total Spent']=df['Total Spent'].astype(float)

In [386]:
df['Quantity'] = df['Quantity'].replace(['ERROR', 'UNKNOWN'], np.nan)
df['Quantity']=df['Quantity'].astype(float)

Para UNKNOWN [ nan 'UNKNOWN' 'ERROR'] y ERROR [ nan 'UNKNOWN' 'ERROR'] calcula la razón entre df['Total Spent']/df['Quantity'] el valor obtenido puede indicar a que item corresponde?

Realiza una gráfica de histograma de los precios por item

In [387]:
df[['Item','Price Per Unit']]

          Item  Price Per Unit
0       Coffee             2.0
1         Cake             3.0
2       Cookie             1.0
3        Salad             5.0
4       Coffee             2.0
...        ...             ...
9995    Coffee             2.0
9996       NaN             NaN
9997    Coffee             2.0
9998    Cookie             1.0
9999  Sandwich             4.0

[9684 rows x 2 columns]

In [388]:
df[df['Item']=='UNKNOWN']

Empty DataFrame
Columns: [Transaction ID, Item, Quantity, Price Per Unit, Total Spent, Payment Method, Location, Transaction Date]
Index: []